name: Deploy code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  provision-batch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  
    - name: Login to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.ARM_CLIENT_ID }} \
          --password ${{ secrets.ARM_CLIENT_SECRET }} \
          --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}
  
    - name: Generate Random IDs
      id: generate_ids
      run: |
        export JOB_ID="job-$RANDOM"
        export TASK_ID="task-$RANDOM"
        echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
        echo "TASK_ID=$TASK_ID" >> $GITHUB_ENV
  
    - name: Create Application Package
      run: |
        zip -r python-app.zip hello_world.py
        az batch application package create \
          --resource-group ${{ secrets.AZ_BATCH_RESOURCE_GROUP }} \
          --name ${{ secrets.AZ_BATCH_ACCOUNT_NAME }} \
          --application-name python-app \
          --package-file python-app.zip \
          --version-name 1.0
  
    - name: Create Batch Job
      run: |
        az batch job create \
          --account-name ${{ secrets.AZ_BATCH_ACCOUNT_NAME }} \
          --account-endpoint ${{ secrets.AZ_BATCH_ACCOUNT_ENDPOINT }} \
          --account-key ${{ secrets.AZ_BATCH_ACCOUNT_KEY }} \
          --id ${{ env.JOB_ID }} \
          --pool-id ${{ secrets.AZ_BATCH_POOL_ID }}
  
    - name: Create Batch Task
      run: |
        az batch task create \
          --job-id ${{ env.JOB_ID }} \
          --task-id ${{ env.TASK_ID }} \
          --command-line '/bin/bash -c "python3 $AZ_BATCH_APP_PACKAGE_python_app_1_0/hello_world.py"' \
          --application-package-references "python-app#1.0" \
          --account-name ${{ secrets.AZ_BATCH_ACCOUNT_NAME }} \
          --account-endpoint ${{ secrets.AZ_BATCH_ACCOUNT_ENDPOINT }} \
          --account-key ${{ secrets.AZ_BATCH_ACCOUNT_KEY }}